[package]
name = "xiayu"
version = "0.1.0-alpha0"
edition = "2018"
authors = ["songww <sww4718168@163.com>"]
description = "ORM powered by SQLx."
documentation = "https://docs.rs/xiayu"
homepage = "https://github.com/songww/xiayu"
keywords = ["orm", "sqlx", "sqlite", "mysql", "mssql", "postgresql"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[package.metadata.docs.rs]
features = ["docs", "all"]

[lib]
name = "xiayu"

[dependencies]
xiayu-derive = { version = "0.1.0-alpha0", path = "./derive" }

thiserror = "1.0"
tracing = "0.1"
hex = "0.4"
sqlx = { version = "0.5" }
either = { version = "1.6", optional = true }
serde_json = { version = "1.0", optional = true }
base64 = { version = "0.13", optional = true }
uuid = { version = "0.8", optional = true, features = [ "v4" ] }
chrono = { version = "0.4", package = "chrono", optional = true }
serde = { version = "1.0", package = "serde", optional = true, features = [ "derive" ] }
num-bigint = { version = "0.4", optional = true }
bigdecimal = { version = "0.2", package = "bigdecimal", optional = true }
derive_more = { version = "0.99", features = ["as_ref", "as_mut", "deref", "deref_mut"] }
indoc = { version = "1.0", optional = true }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["rt"] }

[features]
default = [ "sqlite" ]
docs = [ "sqlx/runtime-tokio-rustls" ]
any = [ "sqlx/any" ]
uuid-type = [ "uuid", "sqlx/uuid" ]
json-type = [ "serde", "serde_json", "base64", "sqlx/json" ]
# serde = [ "dep:serde", "chrono/serde" ]
chrono-type = [ "chrono", "sqlx/chrono" ]
mssql = [ "uuid-type", "chrono-type", "either", "sqlx/mssql", "indoc" ]
mysql = [ "sqlx/mysql" ]
sqlite = [ "sqlx/sqlite" ]
postgres = [ "sqlx/postgres" ]
bigdecimal-type = [ "bigdecimal", "num-bigint", "sqlx/bigdecimal" ]

all = [
    "any",
    "json-type",
    "uuid-type",
    "chrono-type",
    "mssql",
    "mysql",
    "serde",
    "sqlite",
    "postgres",
    "bigdecimal-type",
]

[workspace]
members = [
    "derive"
]
