[package]
name = "xiayu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xiayu"

[dependencies]
xiayu-derive = { version = "0.1.0", path = "./derive" }
derive_more = { version = "0.99.16", features = ["as_ref", "as_mut", "deref", "deref_mut"] }
thiserror = "1.0.26"
either = "1.6.1"
tracing = "0.1.26"
hex = "0.4.3"

[features]
default = [ "mysql", "postgresql" ]
# mssql = []
mysql = []
sqlite = []
postgresql = []

[workspace]
members = [
    "derive"
]
